Feature/create models
tompais/Mobius-API pull request #15
Opened 2020-10-12 20:56 UTC by ezeallio

## Motivación y contexto

## ¿Cómo fue probado?

- [ ] Entorno local
- [ ] Stage

2020-10-12 22:50 UTC, tompais requested changes
Estaría bueno que, además de lo que te comenté, se pruebe en stage-red. Para ver que lo levanta bien la DB de Heroku.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/enums/CategoryType.kt
> +    FIXING,
No sería `FIXATION`?

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/enums/ResourceType.kt
> +    TEXT;
Tengo entendido que los resources van a ser en general archivos que debe procesar el front. No sé si vamos a almacenar texto en sí. Eso quizás lo guardábamos en la tabla de respuestas si te acordás.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
> +    @Column(unique = true, nullable = false, updatable = false)
Falta la annotation `GeneratedValue`. Es para decirle básicamente con qué estrategia genera los ids. 

Usualmente se usa `Identity`. Fijate en los modelos que yo hice así te das cuenta.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
> +    val task: Task,
Para que no te cree una tabla intermedia, falta una annotation acá. Esta es `JoinColumn`.

Te recomiendo que mires [el siguiente link](https://www.baeldung.com/spring-data-rest-relationships).

Pero, básicamente, de este lado vos tendrías que poner algo como: `JoinColumn(name = "task_id")`. De esta manera, esta tabla va a tener una columna con la cual relacionarse y no debería surgir la tabla intermedia que me mencionaste.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
> +    val answer_type: String,
Este atributo debería ir en camelCase. Es decir, debería ser `answerType`. Tengo entendido que hibernate usa un **Strategy Naming** que, solito, pasa todos los nombres de los atributos a snake_case.

Por otro lado, este atributo no tendría que ser un enum también?

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
> +    val id: Long,
Acá también falta el `GeneratedValue`. Podemos también charlar si en verdad queremos ids auto generados para las categorías o si se lo seteamos nosotros. Ya que estos datos los vamos a cargar a mano.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
> +    @field:NotBlank
Al ser un enum, no debería ocurrir que se inserte un valor en blanco a nivel código. Además, con la constraint de nullable = false, lo mitigas casi al máximo eso.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
> +    val type: CategoryType,
Estaba pensando que `CategoryType` podría convertirse en un enum que se llame `Type` y que se encuentre dentro de esta misma clase.

Fijate lo que hice, por ejemplo, con el enum `Status` de la clase `User`. Lo creé adentro de esta clase porque, cuando lo querés usar, tenés que llamarlo de la siguiente forma: `User.Status`. De esa manera queda en claro que es un enum `Status`, que viene de la clase `User`.

Lo mismo podrías hacer acá con este enum.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
> +    val type: CategoryType,
Si no se entendió bien la idea, cualquier cosa lo hablamos por privado 👍

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
> +    @OneToMany(cascade = [ALL])
A esta annotation le falta algo para mapear bien contra una columna y que no se genere una tabla intermedia.

```suggestion
    @OneToMany(mappedBy = "category", cascade = [ALL])
```

Está en el link que te pasé de baeldung sobre las relaciones en Spring JPA.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
> +    val id: Long,
You know what is missing..

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
> +    val tasks: List<Task>
Acá también te dejo para que completes como te enseñé 😄

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
> +    val resources: List<Resource>,
Un juego, por lo que vi, puede no tener recursos. Por lo tanto, este campo habría que hacerlo nullable. Tengo entendido que con poner `List<Resource>?` alcanza. Incluso, podrías ponerle un valor por default. Que sea justamente **null**. Si hacés esto, te recomiendo que muevas este atributo abajo de todo, para tener una inicialización más cómoda.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
> +    val resources: List<Resource>,
Fijate igual si `OneToMany` tiene algún atributo para poner que es opcional.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val id: Long,
Te lo remarco para que te quede jeje 😝

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val game: Game,
Falta el **JoinColumn**

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    @field:NotBlank
Nuevamente, creo que esto es innecesario

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val type: ResourceType,
Misma idea que planteé con el `CategoryType`. Podríamos mover `ResourceType` dentro de esta clase y que solo se llame `Type`. Cuando lo invoques, va a ser `Resource.Type`. En lo personal, creo que es un poco más elegante y te ahorrás un archivo.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val file_name: String
Esto tendríamos que pasarlo a camel 😄 Y estoy dudando si estamos bien con 255. Porque vamos a tener el nombre de un archivo. Puede ser tan grande?

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val type: ResourceType,
Misma idea que planteé con el `CategoryType`. Podríamos mover `ResourceType` dentro de esta clase y que solo se llame `Type`. Cuando lo invoques, va a ser `Resource.Type`. En lo personal, creo que es un poco más elegante y te ahorrás un archivo.

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
> +    val id: Long,
Falta **Ambiente** (? Ah re, re taller web 2 jajaja

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
> +    val game: Game,
Falta **JoinColumn**

2020-10-12 22:50 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
> +class Task(
No falta también que agreguemos, en esta clase, el `OneToMany` optional de `Answers`? No lo veo.

2020-10-13 01:35 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Fijate si se puede importar estáticamente `GenerationType`. Hay una opción en intellij para eso. Algo que dice `Import...` y una sarasa cuando le das click derecho. Yo de hecho seguro lo tengo importado de esa manera.

2020-10-13 01:35 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val fileName: String
Dejamos por las dudas esto con un largo de 255? Sabiendo que solo vamos a guardar el nombre del archivo?

2020-10-13 01:35 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
> +    @Column(nullable = true, length = 255)
El default de la property nullable de la annotation column es **false**. Por lo tanto, no hace falta ponerlo acá.

2020-10-13 03:47 UTC, ezeallio commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val fileName: String
No definimos que nombres tendrán los archivos. Si es un hash para que sean bien aleatorios los nombres y no se pisen, van a ser largos

2020-10-13 10:46 UTC, tompais approved these changes
Ya con lo del file name respondido, yo no veo nada bloqueante.

2020-10-13 10:46 UTC, tompais commented on src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
> +    val fileName: String
Buen punto. Ya me convenciste.

2020-10-14 18:48 UTC, merged